---
- name: Orchestrate NotebookLM Pipeline Data Ingestion
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Dynamically bind execution environment parameters into global runtime memory
      ansible.builtin.set_fact:
        project_root: "/home/jasona/notebooklm/ansible_notebooklm"
        container_image_tag: "quay.io/jasoande/notebooklm-core-engine:latest"
        clients:
          - merck_test

  roles:
    - role: notebooklm
